apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-backend
spec:
  selector:
    matchLabels:
      app: logging-backend
      component: logging-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: logging-backend
        component: logging-backend
    spec:
      containers:
        - name: logging-backend
          image: ohksj77/logging-backend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: logging-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: logging-backend
    component: logging-backend
  type: NodePort
